name: CI
on: [workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Write client_secrets.json
        uses: DamianReeves/write-file-action@v1.3
        with:
          path: app/src/main/assets/client_secrets.json
          contents: ${{ secrets.CLIENT_SECRETS_TEXT }}
          write-mode: overwrite

      - name: Build app
        run: ./gradlew spotlessCheck assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: TachiyomiSY-${{ github.sha }}
          path: app/build/outputs/apk/debug/app-universal-debug.apk
